server:
  port: 8610

spring:
  application:
    name: eureka-producer

eureka:
  client:
    service-url:
      # ????????
      defaultZone: http://10.11.93.121:8601/eureka/,http://10.0.19.158:8601/eureka/,http://10.0.19.168:8601/eureka/
