server:
  port: 8620

spring:
  application:
    name: eureka-consumer

eureka:
  client:
    service-url:
      # ????????
      defaultZone: http://localhost:8601/eureka,http://localhost:8602/eureka/,http://localhost:8603/eureka/
