# ?????? (???)
server:
  port: 8601
eureka:
  instance:
    #需要给电脑配置对应的多个hostname，此项目是配了127.0.0.1 eureka-server、1、2
    hostname: eureka-server
    #???? default is 30
    leaseRenewalIntervalInSeconds: 30
  client:
    # ?????Eureka Server??????,???true.?????????Eureka Server,????????Eureka Server?????,?????false
    fetch-registry: false
    # ??????????Eureka Server,???true.????????Eureka Server,?????false.
    register-with-eureka: false

    #false表示不向注册中心注册自己。
    registerWithEureka: false
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetchRegistry: false


    service-url:
      # ???Eureka Server???,??????????????????.???http://localhost:8601/eureka/;???????','??.
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka-server1:8602/eureka/,http://eureka-server2:8603/eureka/

    server:
      #???? ????true
      enable-self-preservation: true
      #???? default is 0.85 we can set the value to 0.49
      renewalPercentThreshold: 0.49
